//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchizitiiExtended
    {
        public int ID_ACHIZITIE { get; set; }
        public string Nume_Produs { get; set; }
        public Nullable<int> Numar_de_bucati { get; set; }
        public Nullable<decimal> Pret_Unitar { get; set; }
        public string Nume { get; set; }
        public string Adresa_Depozit { get; set; }
        public int Numar_Factura { get; set; }
    }
}
