//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsExtended
    {
        public int ID_COMANDA_DETALII { get; set; }
        public Nullable<int> ID_COMANDA { get; set; }
        public string Denumire { get; set; }
        public Nullable<int> Cantitate { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    }
}
