//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plati_servicii
    {
        public int ID_PLATA { get; set; }
        public Nullable<int> ID_UTILITATE { get; set; }
        public Nullable<decimal> Suma { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ID_SUCURSALA { get; set; }
        public Nullable<int> ID_FACTURA { get; set; }
    
        public virtual Facturi Facturi { get; set; }
        public virtual Utilitati Utilitati { get; set; }
    }
}
