//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarii
    {
        public int ID_ANGAJAT { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Functie { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<decimal> Salariu { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
