//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_de_plata
    {
        public int ID_PLATA { get; set; }
        public Nullable<int> ID_ANGAJAT { get; set; }
        public Nullable<decimal> Suma { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string TIP_PLATA { get; set; }
    
        public virtual Angajati Angajati { get; set; }
    }
}
