//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_USER { get; set; }
        public Nullable<int> ID_ANGAJAT { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
    
        public virtual Angajati Angajati { get; set; }
    }
}
